#!/bin/sh

# Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies). 
# All rights reserved.

PRGDIR=`dirname "$0"`
PRGDIR=`cd "$PRGDIR"; pwd`

[ -z "$QMAKESPEC" ] && export QMAKESPEC=$PRGDIR/qt/mkspecs/symbian-sbsv2

"$PRGDIR/qt/uic" "$@"
