#
# Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies). 
# All rights reserved.
#
# Description: exporting of *.meta file via cmaker
#
 
MAKEFILE = /sf/mw/qt/group/cmaker/makefile
 
# Place the first target as the default target which is executed from this level 

export_template_files :: template_makefiles
          
include include_template.mk 
