# Description: exporting of *.meta file via cmaker
#
 
MAKEFILE = /sf/mw/qt/src/s60installs/deviceconfiguration/cmaker/makefile
 
# Place the first target as the default target which is executed from this level 

export_template_files :: template_makefiles
          
include include_template.mk 
